import { Topic, User, GiftRecord } from './types';

export const COUNTRY_CODES = [
  { code: '+86', name: '中国' },
  { code: '+1', name: '美国' },
  { code: '+81', name: '日本' },
  { code: '+44', name: '英国' },
];

export const TOPICS: Topic[] = [
  {
    id: '1',
    title: '今天的城市声音',
    description: '拍下你所在城市此刻最有记忆点的声音和画面。',
    prompt: '现在听到的声音',
    creator: '林野',
    status: 'forming',
    joinedCount: 6,
    targetCount: 8,
    likes: '8.2k',
    city: '上海',
    tone: 'blue',
    mode: '限时现场拍摄',
    deadline: '01:26:14',
    durationLimit: 3,
    image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=900&h=1200&fit=crop',
  },
  {
    id: '2',
    title: '今天真实的早餐桌',
    description: '不用精致，记录你今天真正吃下的第一口食物。',
    prompt: '第一口食物',
    creator: 'Mia',
    status: 'completed',
    joinedCount: 10,
    targetCount: 10,
    likes: '12.8k',
    shares: '4.2k',
    bookmarks: '3.1k',
    city: '杭州',
    tone: 'amber',
    mode: '先发后看',
    deadline: '已成圈',
    durationLimit: 5,
    image: 'https://images.unsplash.com/photo-1495195134817-aeb325a55b65?w=900&h=1200&fit=crop',
  },
  {
    id: '3',
    title: '下班后的三十分钟',
    description: '每个人拍一段下班后的真实空档，拼成一条城市切片。',
    prompt: '下班后的此刻',
    creator: '周屿',
    status: 'forming',
    joinedCount: 4,
    targetCount: 10,
    likes: '5.4k',
    city: '深圳',
    tone: 'green',
    mode: '15 秒原声视频',
    deadline: '03:42:08',
    durationLimit: 8,
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?w=900&h=1200&fit=crop',
  },
  {
    id: '4',
    title: '深夜的一盏灯',
    description: '记录你今晚还亮着的那盏灯，可能是路灯、台灯，也可能是便利店。',
    prompt: '深夜还亮着的光',
    creator: '南川',
    status: 'forming',
    joinedCount: 3,
    targetCount: 8,
    likes: '2.9k',
    city: '成都',
    tone: 'blue',
    mode: '3 秒现场片段',
    deadline: '05:18:22',
    durationLimit: 3,
    image: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?w=900&h=1200&fit=crop',
  },
  {
    id: '5',
    title: '早高峰的地铁窗',
    description: '拍下车窗里一闪而过的城市表情，拼成一条早高峰的路线。',
    prompt: '地铁窗外的瞬间',
    creator: 'Echo',
    status: 'forming',
    joinedCount: 7,
    targetCount: 12,
    likes: '3.6k',
    city: '北京',
    tone: 'green',
    mode: '原声短视频',
    deadline: '02:11:45',
    durationLimit: 6,
    image: 'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=900&h=1200&fit=crop',
  },
  {
    id: '6',
    title: '周末的桌面',
    description: '不用整理，拍下你此刻真实的桌面，让一群人的周末状态同屏出现。',
    prompt: '此刻桌面',
    creator: '阿泽',
    status: 'forming',
    joinedCount: 2,
    targetCount: 6,
    likes: '4.1k',
    city: '广州',
    tone: 'amber',
    mode: '照片或短视频',
    deadline: '07:30:10',
    durationLimit: 5,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=900&h=1200&fit=crop',
  },
  {
    id: '7',
    title: '雨后路面的倒影',
    description: '找一处雨后的倒影，记录城市被水面重新排列的一秒。',
    prompt: '雨后的倒影',
    creator: '小北',
    status: 'forming',
    joinedCount: 5,
    targetCount: 9,
    likes: '6.7k',
    city: '南京',
    tone: 'blue',
    mode: '限时现场拍摄',
    deadline: '04:05:33',
    durationLimit: 4,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=900&h=1200&fit=crop',
  },
  {
    id: '8',
    title: '今天路过的招牌',
    description: '拍下你今天最有记忆点的店招、路牌或手写告示。',
    prompt: '路过的文字',
    creator: '梨落',
    status: 'forming',
    joinedCount: 8,
    targetCount: 10,
    likes: '7.5k',
    city: '苏州',
    tone: 'green',
    mode: '照片优先',
    deadline: '00:58:49',
    durationLimit: 3,
    image: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=900&h=1200&fit=crop',
  },
  {
    id: '9',
    title: '午后三点的影子',
    description: '记录下午三点左右落在地面、墙面或桌面的影子。',
    prompt: '午后的影子',
    creator: 'Kira',
    status: 'completed',
    joinedCount: 8,
    targetCount: 8,
    likes: '9.4k',
    shares: '2.1k',
    bookmarks: '1.5k',
    city: '厦门',
    tone: 'amber',
    mode: '同步解锁',
    deadline: '已成圈',
    durationLimit: 4,
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=900&h=1200&fit=crop',
  },
  {
    id: '10',
    title: '便利店门口的人',
    description: '不同城市便利店门口的一分钟，拼出夜晚生活的边角。',
    prompt: '便利店门口',
    creator: '老陈',
    status: 'completed',
    joinedCount: 12,
    targetCount: 12,
    likes: '15.2k',
    shares: '5.6k',
    bookmarks: '4.8k',
    city: '重庆',
    tone: 'blue',
    mode: '合集成圈',
    deadline: '已成圈',
    durationLimit: 6,
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=900&h=1200&fit=crop',
  },
  {
    id: '11',
    title: '厨房里的蒸汽',
    description: '拍下锅边、杯口、早餐摊前升起的热气，记录生活刚刚发生。',
    prompt: '一团蒸汽',
    creator: 'Momo',
    status: 'completed',
    joinedCount: 9,
    targetCount: 9,
    likes: '10.1k',
    shares: '0',
    bookmarks: '0',
    city: '武汉',
    tone: 'amber',
    mode: '先发后看',
    deadline: '已成圈',
    durationLimit: 5,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=900&h=1200&fit=crop',
  },
];

export const USER_PROFILES: Record<string, User> = {
  'linye': {
    id: 'linye',
    name: '林野',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=128&h=128&fit=crop',
    bio: '@linye · 喜欢收集城市里不被注意的片段。',
    streak: 12,
    followers: 2400,
    following: 128,
  },
  'mia': {
    id: 'mia',
    name: 'Mia',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=128&h=128&fit=crop',
    bio: '简单生活，认真吃饭。',
    streak: 30,
    followers: 8900,
    following: 240,
  }
};

export const CONVERSATIONS = [
  { id: '1', name: '林野', lastMessage: '我刚拍了一段 3 秒片段，顺手把声音也录进去了。', time: '09:41', unread: 2, type: 'person' },
  { id: '2', name: 'Mia', lastMessage: '谢谢你给《今天真实的早餐桌》送的礼物。', time: '昨天', unread: 0, type: 'person' },
  { id: '3', name: '亲密邀请', lastMessage: '林野邀请你绑定「真爱」关系。', time: '昨天', unread: 1, type: 'relation' },
  { id: '4', name: '系统通知', lastMessage: '《下班后的三十分钟》已完成，点进去看成品。', time: '昨天', unread: 1, type: 'system' },
  { id: '5', name: '礼物助手', lastMessage: '你收到 1 个「灵感胶片」礼物。', time: '周一', unread: 0, type: 'gift' },
];

export const GIFTS = [
  { name: '灵感胶片', price: 180, icon: '🎞️' },
  { name: '城市明信片', price: 320, icon: '📮' },
  { name: '成圈烟花', price: 560, icon: '🎆' },
  { name: '共创徽章', price: 980, icon: '🎖️' },
  { name: '星轨戒指', price: 1280, icon: '💍' },
  { name: '积分胶囊', price: 68, icon: '💊' },
  { name: '感谢卡', price: 10, icon: '💌' },
  { name: '记录仪式', price: 240, icon: '🎬' },
];

export const SHARE_FRIENDS = [
  { id: '1', name: '小明', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Friend1' },
  { id: '2', name: 'Lisa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Friend2' },
  { id: '3', name: '阿强', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Friend3' },
  { id: '4', name: 'Emma', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Friend4' },
  { id: '5', name: '老李', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Friend5' },
  { id: '6', name: '小红', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Friend6' },
];

export const MOCK_GIFT_RECORDS: GiftRecord[] = [
  { id: 'g1', topicId: '1', userId: 'u1', userName: '小明', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Friend1', giftName: '灵感胶片', giftValue: 180 },
  { id: 'g2', topicId: '1', userId: 'u2', userName: 'Lisa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Friend2', giftName: '城市明信片', giftValue: 320 },
  { id: 'g3', topicId: '1', userId: 'u3', userName: '阿强', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Friend3', giftName: '成圈烟花', giftValue: 560 },
  { id: 'g4', topicId: '1', userId: 'u4', userName: 'Emma', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Friend4', giftName: '灵感胶片', giftValue: 180 },
];

export const SHOP_ITEMS = [
  { name: 'DR 帆布袋', price: '680', unit: '积分' },
  { name: '香氛挂片', price: '320', unit: '积分' },
  { name: '限定贴纸包', price: '120', unit: '积分' },
  { name: '银色手机挂绳', price: '880', unit: '积分' },
];

export const CURRENT_USER: User = {
  id: 'me',
  name: '迪儿6317B6SG',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=128&h=128&fit=crop',
  bio: '用一句话介绍一下自己',
  streak: 7,
  followers: 1200,
  following: 86,
  gender: '男',
};
